In [ ]:
import os
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv(r"C:\Users\KRISHAN\Downloads\data science\pandas\project1\Used_Bikes.csv")

In [ ]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df.age

0         3.0
1         4.0
2         8.0
3         4.0
4         3.0
         ...
32643     4.0
32644     9.0
32645     6.0
32646    16.0
32647    13.0
Name: age, Length: 32648, dtype: float64

In [ ]:
df[["brand"]]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [ ]:
df[["owner"]]

             owner
0      First Owner
1      First Owner
2      First Owner
3      First Owner
4      First Owner
...            ...
32643  First Owner
32644  First Owner
32645  First Owner
32646  First Owner
32647  First Owner

[32648 rows x 1 columns]

In [ ]:
df[["city"]]

            city
0      Ahmedabad
1          Delhi
2          Delhi
3      Bangalore
4      Bangalore
...          ...
32643      Delhi
32644     Karnal
32645      Delhi
32646     Jaipur
32647       Pune

[32648 rows x 1 columns]

In [ ]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [ ]:
df["bike_name"].unique()

<StringArray>
[      'TVS Star City Plus Dual Tone 110cc',
              'Royal Enfield Classic 350cc',
                     'Triumph Daytona 675R',
                     'TVS Apache RTR 180cc',
     'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
                         'Yamaha FZs 150cc',
            'Honda CB Hornet 160R  ABS DLX',
      'Hero Splendor Plus Self Alloy 100cc',
        'Royal Enfield Thunderbird X 350cc',
 'Royal Enfield Classic Desert Storm 500cc',
 ...
                 'Bajaj Discover150S 150cc',
                       'Hero i Smart 125cc',
               'Hero Splendor Plus  100 cc',
                'Hero Splendor Plus 100 CC',
                      'Hero Karizma 223 cc',
                         'TVS MAX 4R 110cc',
                   'Mahindra Pantero 110cc',
                      'Hero Ambition 135cc',
                'Honda CBR 250R Repsol ABS',
                'Hero Hunk Rear Disc 150cc']
Length: 471, dtype: str

In [ ]:
df["owner"].nunique()

4

In [ ]:
df["brand"].nunique()

23

In [ ]:
df["brand"].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(25324)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [ ]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
# df.drop("city",axis=1,inplace=True)
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
df.drop(["city","bike_name"],axis=1,inplace=True)

In [ ]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [ ]:
char=df.select_dtypes(include='object')
char

C:\Users\KRISHAN\AppData\Local\Temp\ipykernel_4220\171249912.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char=df.select_dtypes(include='object')

            owner            brand
0     First Owner              TVS
1     First Owner    Royal Enfield
2     First Owner          Triumph
3     First Owner              TVS
4     First Owner           Yamaha
...           ...              ...
9362  First Owner             Hero
9369  First Owner            Bajaj
9370  First Owner  Harley-Davidson
9371  First Owner            Bajaj
9372  First Owner            Bajaj

[7324 rows x 2 columns]

In [ ]:
num=df.select_dtypes(exclude='object')
num

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [ ]:
char['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [ ]:
owner_dict = {
    'First Owner':1, 
    'Second Owner':2, 
    'Third Owner':3, 
    'Fourth Owner Or More':4
              }

char['owner']=char['owner'].map(owner_dict)

In [ ]:
char

      owner            brand
0         1              TVS
1         1    Royal Enfield
2         1          Triumph
3         1              TVS
4         1           Yamaha
...     ...              ...
9362      1             Hero
9369      1            Bajaj
9370      1  Harley-Davidson
9371      1            Bajaj
9372      1            Bajaj

[7324 rows x 2 columns]

In [ ]:
char['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [ ]:
owner_dict = {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
              }

char['brand']=char['brand'].map(owner_dict)

char

      owner  brand
0         1      1
1         1      2
2         1      3
3         1      1
4         1      4
...     ...    ...
9362      1      6
9369      1      7
9370      1     15
9371      1      7
9372      1      7

[7324 rows x 2 columns]

In [ ]:
total_df=pd.concat([char,num],axis=1)

total_df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
9362      1      6   25000.0     48587.0  8.0  150.0
9369      1      7   35000.0     60000.0  9.0  220.0
9370      1     15  450000.0      3430.0  4.0  750.0
9371      1      7  139000.0     21300.0  4.0  400.0
9372      1      7   80000.0      7127.0  5.0  220.0

[7324 rows x 6 columns]

In [ ]:
total_df.duplicated().sum()

np.int64(18)

In [ ]:
total_df.drop_duplicates(inplace=True)

In [ ]:
total_df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
9362      1      6   25000.0     48587.0  8.0  150.0
9369      1      7   35000.0     60000.0  9.0  220.0
9370      1     15  450000.0      3430.0  4.0  750.0
9371      1      7  139000.0     21300.0  4.0  400.0
9372      1      7   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [ ]:
total_df.isnull().sum()

owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [ ]:
df

In [ ]:
total_df.to_csv('Used_Bikes_Cleaned.csv')

In [ ]:
x=total_df.drop('price',axis=1)
x

      owner  brand  kms_driven  age  power
0         1      1     17654.0  3.0  110.0
1         1      2     11000.0  4.0  350.0
2         1      3       110.0  8.0  675.0
3         1      1     16329.0  4.0  180.0
4         1      4     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
9362      1      6     48587.0  8.0  150.0
9369      1      7     60000.0  9.0  220.0
9370      1     15      3430.0  4.0  750.0
9371      1      7     21300.0  4.0  400.0
9372      1      7      7127.0  5.0  220.0

[7306 rows x 5 columns]

In [ ]:
import pandas as pd
import numpy as np
import os
df =pd.read_csv('Used_Bikes.csv')

In [ ]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
tvs_df=df[df['brand']=='TVS']
tvs_df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [ ]:
tvs_first_owner_df =tvs_df[tvs_df['owner']=='First Owner']

In [ ]:
tvs_first_owner_df[tvs_first_owner_df['kms_driven']>=5000]

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [ ]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [ ]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [ ]:
royal_df=df[df['brand']=='Royal Enfield']
royal_df

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,First Owner,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,First Owner,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
32601,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32614,Royal Enfield Bullet Electra 350cc,105000.0,Delhi,20000.0,First Owner,4.0,350.0,Royal Enfield
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield

In [ ]:
royal_first_owner_df =royal_df[royal_df['owner']=='First Owner']

In [ ]:
age =royal_first_owner_df[royal_first_owner_df['kms_driven']<=5000]

In [ ]:
price =age[age['age']>=1]

In [ ]:
price[price['price']==200000]

Empty DataFrame
Columns: [bike_name, price, city, kms_driven, owner, age, power, brand]
Index: []

In [ ]:
royal_data=df[(df['brand']=='Royal Enfield')&
            (df['owner']=='First Owner')&
             (df['kms_driven']<=50000)&
              (df['age']<=2)&
               (df['price']<=200000)
                ]
royal_data

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7422,Royal Enfield Himalayan 410cc Sleet ABS,175000.0,Alipore,1800.0,First Owner,2.0,410.0,Royal Enfield
7559,Royal Enfield Bullet 500cc,170000.0,Delhi,8015.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [ ]:
df.query("brand == 'Royal Enfield' and owner == 'First Owner' and kms_driven <= 500000 and age <= 2 and price <= 200000")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7422,Royal Enfield Himalayan 410cc Sleet ABS,175000.0,Alipore,1800.0,First Owner,2.0,410.0,Royal Enfield
7559,Royal Enfield Bullet 500cc,170000.0,Delhi,8015.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [ ]:
hero_data=df[(df['brand']=='Hero')&
            (df['owner']=='Second Owner')&
             (df['kms_driven']>=20000)&
              (df['age']>=1)&
               (df['price']>=2000)
                ]
hero_data

,bike_name,price,city,kms_driven,owner,age,power,brand
74,Hero Karizma ZMR 223cc,55786.0,Surat,68000.0,Second Owner,7.0,223.0,Hero
592,Hero Splendor Plus 100cc,32000.0,Pune,21884.0,Second Owner,8.0,100.0,Hero
805,Hero Ignitor 125cc,23000.0,Jhansi,25000.0,Second Owner,6.0,125.0,Hero
1046,Hero Splendor Pro 100cc,22100.0,Jhansi,24000.0,Second Owner,7.0,100.0,Hero
1068,Hero CBZ Xtreme 150cc,34500.0,Pune,80000.0,Second Owner,10.0,150.0,Hero
...,...,...,...,...,...,...,...,...
32547,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32566,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32585,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32604,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero

In [ ]:
# os.rename('krishan.csv','Cleaned_Used_Bikes.csv')

In [ ]:
df

NameError: name 'df' is not defined